# change the followings to match your Github username and repo name
baseurl: "/charting-first-encounters" # the name of your github repo
url: "https://christian-egan.github.io" # the url of your github pages (change BCDigSchol to your username)

# site information used in page title, meta data etc.
title: "Charting First Encounters"
description: Mapping George Vancouver's Encounters with Puget Sound's Native Peoples

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: home
  - title: Background
    submenu:
      - title: Maps and Project Background
        link: scholarship
      - title: New Map
        link: newmap
      - title: Original Map
        link: oldmap
  - title: Methodology
    link: methodology
  - title: Analysis
    submenu:
    - title: Conclusions
      link: conclusions
    - title: Pedagogy
      link: pedagogy
  - title: Bibliography
    link: bibliography

# sets whether a search bar appears on the site header
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: This project acknowledges the continued presence of the Indigenous peoples of Puget Sound, whose ancestral lands were mapped in the creation of this project: the Hulʼqumiʼnum Treaty Group, the Confederated Tribes of the Umatilla Indian Reservation, the S'Klallam Tribes, the Chimacum people, the Suquamish Tribe, the Tulalip Tribes, the Twana and Skokomish peoples, and others.
footer-submessage:  By Christian Egan, with the Digital Scholarship Group, Boston College | CC BY-NC License
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
